# Generated by Django 6.0.1 on 2026-07-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_transaccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion_facturacion', models.CharField(max_length=150)),
                ('numero_tarjeta', models.CharField(max_length=19)),
                ('fecha_vencimiento', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('contacto_nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email_corporativo', models.EmailField(max_length=254)),
                ('direccion_fiscal', models.CharField(max_length=150)),
                ('cuenta_bancaria_iban', models.CharField(max_length=34)),
            ],
        ),
    ]
