# Generated by Django 6.0.1 on 2026-07-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cliente_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente Común')], default='cliente', max_length=15),
        ),
    ]
